baseURL = "https://main.dui7if5d6agqo.amplifyapp.com/"
languageCode = "en"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
theme = "hugo-initio"

[params]
    name = "Diego Miret Halffter"
    description = "A mystery person"
    email = "diego@yellowcomet.es"
    phone = "+34 687263299"
    address = "Jazmin 146 1B, Madrid, Alcobendas 28109"
    year = 2023
    avatar = "images/link.png"
    avatarclass = "circle"
    background = ""
    banner = "images/zeldabanner.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Diego Miret Halffter"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/diego.miret.9"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/Yellow_Comet13"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/diegomiret13"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://es.linkedin.com/in/diego-miret-halffter-a34063129"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/YellowComet"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
